# Generated by Django 3.0.8 on 2020-10-19 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='data', to=settings.AUTH_USER_MODEL),
        ),
    ]
